recipe: "regression/v1"
target_col: "Age"
primary_metric: "root_mean_squared_error"

steps:
  ingest: {{INGEST_CONFIG}}

  split:
    split_ratios: [0.75, 0.125, 0.125]
    
  transform:
    using: "custom"
    transformer_method: "transformer_fn"

  train:
    estimator_method: "estimator_fn"  
    estimator_params: {{MODEL_CONFIG.RandomForestRegressor}}  
  evaluate:
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 10.0

  register:
    allow_non_validated_model: True
