INGEST_CONFIG:
  location: data/diabetes.parquet
  using: parquet
MODEL_CONFIG:
  DecisionTreeRegressor:
    estimator: DecisionTreeRegressor
    max_depth: 5
    min_samples_split: 2
    random_state: 42
  GradientBoostingRegressor:
    estimator: GradientBoostingRegressor
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 100
  KNeighborsRegressor:
    estimator: KNeighborsRegressor
    n_neighbors: 5
    weights: uniform
  LinearRegression:
    estimator: LinearRegression
    fit_intercept: true
  RandomForestRegressor:
    estimator: RandomForestRegressor
    max_depth: 10
    n_estimators: 50
    random_state: 42
  SupportVectorRegressor:
    C: 1.0
    estimator: SVR
    kernel: rbf
experiment:
  artifact_location: ./metadata/mlflow/mlartifacts
  name: RandomForestRegressor_Experiment
  tracking_uri: http://127.0.0.1:5000
model_registry:
  model_name: Regression_Model
